server:
  port: 8088
  servlet:
    context-path: /message
dubbo:
  application:
    name: message
#    registry: zookeeper://127.0.0.1:2181
  registry:
      protocol: zookeeper
      address: 127.0.0.2
      port: 2222
